// 用語の関係マップ（手キュレーション部分）。
// カテゴリ（テーマ分類）と、意味的なエッジ（関係）を定義。
// これに加えて「同じ論文に出た用語どうし」の自動エッジ（共起）をランタイムで合成する。
// term 名は data/papers.json の terms[].term と完全一致させること。

export interface GraphCategory {
  key: string;
  label: string;
  color: string;
  terms: string[];
}

export interface CuratedEdge {
  from: string;
  to: string;
  label?: string;
}

export const CATEGORIES: GraphCategory[] = [
  {
    key: "instability",
    label: "不安定現象",
    color: "#b4451f",
    terms: [
      "サージ",
      "回転失速",
      "B パラメータ",
      "スパイク型回転失速",
      "回転失速の前駆現象",
      "モード波型前駆現象 (modal-wave precursor)",
      "深いサージ (deep surge)",
      "Moore–Greitzer モデル",
      "サージ余裕 (surge margin)",
      "失速余裕",
      "渦崩壊 (vortex breakdown)",
      "逆流（backflow）",
      "ブロッケージ (blockage)",
      "先端すき間渦の前縁越え",
      "渦運動学（vortex kinematics）",
      "失速境界",
    ],
  },
  {
    key: "loss",
    label: "損失機構",
    color: "#1a5e54",
    terms: [
      "エントロピー生成",
      "エントロピー損失係数",
      "全圧損失係数",
      "翼型損失",
      "D因子 (D-factor)",
      "混合損失",
      "端壁（二次流れ）損失",
      "翼端漏れ",
      "境界層",
      "翼端漏れ渦",
      "翼端漏れ流れ (tip leakage flow)",
      "先端すき間流れ（tip clearance flow）",
      "軸方向渦度 (streamwise vorticity)",
      "表面粗さ (surface roughness)",
      "衝撃波境界層干渉 (SBLI)",
    ],
  },
  {
    key: "flow",
    label: "流れ要素・装置",
    color: "#4a6fa5",
    terms: [
      "遠心圧縮機",
      "多段軸流圧縮機",
      "放射ディフューザ",
      "入射角",
      "せん断層",
      "ターボチャージャー",
      "平面翼列・環状翼列",
      "よどみ点 (stagnation point)",
      "二面角 (dihedral angle)",
      "スロットル弁",
      "静翼角度",
    ],
  },
  {
    key: "method",
    label: "数値解析・手法",
    color: "#7a6a9b",
    terms: [
      "CFD",
      "LES",
      "WALEモデル",
      "サロゲートモデル",
      "CNN",
      "次元削減",
      "転移学習",
      "不確かさ",
      "URANS（k-ω SST）",
      "遺伝的アルゴリズム",
      "動的モード分解 (DMD)",
      "全周非定常RANS (full-annulus URANS)",
      "RANS（レイノルズ平均ナビエ・ストークス）",
      "SST k-ω",
      "k-ω SST乱流モデル",
      "MRF（移動基準座標系）",
      "ブレード通過周波数 (blade passing frequency)",
      "区分的3次多項式",
      "ブシネスク仮説",
      "渦粘性",
      "Q基準 (Q-criterion)",
    ],
  },
  {
    key: "theory",
    label: "設計理論・流れ面",
    color: "#8a6d3b",
    terms: [
      "S1流れ面（第一種）",
      "S2流れ面（第二種）",
      "相対流れ面",
      "子午面",
      "スルーフロー理論",
      "主方程式",
      "非粘性流体",
      "順問題・逆問題",
      "性能特性（特性曲線）",
      "負荷係数 / 流量係数",
    ],
  },
  {
    key: "control",
    label: "流れ制御・剥離",
    color: "#b9763a",
    terms: [
      "境界層剥離",
      "再付着",
      "シンセティックジェット（合成噴流）",
      "能動流れ制御（AFC）",
      "迎え角（AoA）",
      "ケーシングトリートメント",
      "軸方向スロット型ケーシングトリートメント (axial slot casing treatment)",
      "自己再循環",
      "前縁剥離 (leading-edge separation)",
      "3次元境界層剥離",
      "運動量係数 Cμ",
      "無次元周波数 F⁺",
      "渦放出周波数",
      "ハブコーナー剥離",
      "コーナー剥離",
      "逆圧力勾配 (adverse pressure gradient)",
      "限界流線 (limiting streamline)",
    ],
  },
  {
    key: "secondary",
    label: "二次流れ・エンドウォール",
    color: "#5f7a8a",
    terms: [
      "二次流れ",
      "馬蹄形渦（horseshoe vortex）",
      "エンドウォール",
      "エンドウォールフェンス",
      "コンタリング（endwall contouring）",
      "エンドウォール輪郭",
    ],
  },
  {
    key: "transition",
    label: "遷移・伝熱",
    color: "#8f5a6d",
    terms: ["層流", "乱流", "層流-乱流遷移", "熱伝達"],
  },
  {
    key: "wake",
    label: "風車・ウェイク",
    color: "#6b8457",
    terms: [
      "後流（ウェイク）",
      "ニアウェイク／ファーウェイク",
      "ウェイクメアンダリング",
      "アクチュエータディスク",
      "大気境界層（ABL）",
      "ヘルマン指数",
      "先端速度比（tip speed ratio, λ）",
      "出力係数（power coefficient, Cp）",
      "推力係数（thrust coefficient, Ct）",
    ],
  },
];

export const CURATED_EDGES: CuratedEdge[] = [
  { from: "サージ", to: "回転失速", label: "両不安定" },
  { from: "B パラメータ", to: "サージ", label: "支配" },
  { from: "B パラメータ", to: "回転失速", label: "支配" },
  { from: "翼端漏れ", to: "入射角", label: "悪化" },
  { from: "エントロピー生成", to: "エントロピー損失係数", label: "定義" },
  { from: "エントロピー損失係数", to: "全圧損失係数", label: "関係" },
  { from: "境界層", to: "翼型損失", label: "起源" },
  { from: "境界層", to: "せん断層" },
  { from: "翼型損失", to: "エントロピー生成", label: "損失" },
  { from: "端壁（二次流れ）損失", to: "エントロピー生成", label: "損失" },
  { from: "翼端漏れ", to: "エントロピー生成", label: "損失" },
  { from: "混合損失", to: "エントロピー生成", label: "損失" },
  { from: "CFD", to: "LES", label: "一種" },
  { from: "CFD", to: "サロゲートモデル", label: "代替" },
  { from: "サロゲートモデル", to: "CNN", label: "実装" },
  { from: "サロゲートモデル", to: "次元削減" },
  { from: "サロゲートモデル", to: "転移学習" },
  { from: "サロゲートモデル", to: "不確かさ" },
  { from: "遠心圧縮機", to: "サージ", label: "発生" },
  { from: "遠心圧縮機", to: "回転失速", label: "発生" },
  { from: "せん断層", to: "回転失速", label: "渦誘起" },
  { from: "多段軸流圧縮機", to: "サロゲートモデル", label: "対象" },
  { from: "S1流れ面（第一種）", to: "S2流れ面（第二種）", label: "二流れ面" },
  { from: "相対流れ面", to: "S1流れ面（第一種）" },
  { from: "相対流れ面", to: "S2流れ面（第二種）" },
  { from: "S2流れ面（第二種）", to: "スルーフロー理論", label: "基礎" },
  { from: "迎え角（AoA）", to: "境界層剥離", label: "増で誘発" },
  { from: "境界層剥離", to: "再付着", label: "制御で回復" },
  { from: "シンセティックジェット（合成噴流）", to: "境界層剥離", label: "抑制" },
  { from: "能動流れ制御（AFC）", to: "シンセティックジェット（合成噴流）", label: "手段" },
  { from: "能動流れ制御（AFC）", to: "遺伝的アルゴリズム", label: "最適化" },
  { from: "境界層剥離", to: "境界層", label: "から発達" },
  { from: "二次流れ", to: "馬蹄形渦（horseshoe vortex）", label: "起源" },
  { from: "馬蹄形渦（horseshoe vortex）", to: "エンドウォール", label: "境界層から発達" },
  { from: "二次流れ", to: "端壁（二次流れ）損失", label: "損失化" },
  { from: "エンドウォールフェンス", to: "二次流れ", label: "抑制" },
  // --- 不安定現象（スパイク失速・Moore–Greitzer・余裕） ---
  { from: "スパイク型回転失速", to: "回転失速", label: "一型" },
  { from: "回転失速の前駆現象", to: "スパイク型回転失速", label: "前触れ" },
  { from: "深いサージ (deep surge)", to: "サージ", label: "強い形態" },
  { from: "Moore–Greitzer モデル", to: "サージ", label: "予測" },
  { from: "Moore–Greitzer モデル", to: "回転失速", label: "予測" },
  { from: "B パラメータ", to: "Moore–Greitzer モデル", label: "指標" },
  { from: "サージ余裕 (surge margin)", to: "サージ", label: "距離" },
  { from: "失速余裕", to: "回転失速", label: "距離" },
  { from: "失速余裕", to: "サージ余裕 (surge margin)", label: "類概念" },
  // --- 翼端漏れ渦の連鎖（Furukawa 1999）と制御（Yaylak 2026） ---
  { from: "先端すき間流れ（tip clearance flow）", to: "翼端漏れ渦", label: "巻き上がり" },
  { from: "翼端漏れ流れ (tip leakage flow)", to: "翼端漏れ渦", label: "巻き上がり" },
  { from: "翼端漏れ", to: "翼端漏れ渦", label: "同源" },
  { from: "翼端漏れ渦", to: "渦崩壊 (vortex breakdown)", label: "失速近傍で" },
  { from: "渦崩壊 (vortex breakdown)", to: "逆流（backflow）", label: "随伴" },
  { from: "渦崩壊 (vortex breakdown)", to: "ブロッケージ (blockage)", label: "生成" },
  { from: "ブロッケージ (blockage)", to: "回転失速", label: "誘発" },
  { from: "ケーシングトリートメント", to: "翼端漏れ渦", label: "制御" },
  { from: "ケーシングトリートメント", to: "失速余裕", label: "拡大" },
  { from: "自己再循環", to: "ケーシングトリートメント", label: "一種" },
  { from: "軸方向スロット型ケーシングトリートメント (axial slot casing treatment)", to: "ケーシングトリートメント", label: "一種" },
  { from: "モード波型前駆現象 (modal-wave precursor)", to: "回転失速の前駆現象", label: "一型" },
  { from: "D因子 (D-factor)", to: "境界層剥離", label: "予測指標" },
  { from: "前縁剥離 (leading-edge separation)", to: "スパイク型回転失速", label: "引き金" },
  // --- 遷移・伝熱（Mayle 1991） ---
  { from: "層流", to: "層流-乱流遷移", label: "始点" },
  { from: "層流-乱流遷移", to: "乱流", label: "終点" },
  { from: "層流-乱流遷移", to: "境界層", label: "内で進行" },
  { from: "層流-乱流遷移", to: "熱伝達", label: "左右" },
  // --- 風車・ウェイク（Sanderse 2011 / Vilotijević 2026） ---
  { from: "ニアウェイク／ファーウェイク", to: "後流（ウェイク）", label: "区分" },
  { from: "ウェイクメアンダリング", to: "後流（ウェイク）", label: "揺動" },
  { from: "アクチュエータディスク", to: "後流（ウェイク）", label: "模擬" },
  { from: "大気境界層（ABL）", to: "後流（ウェイク）", label: "流入条件" },
  { from: "ヘルマン指数", to: "大気境界層（ABL）", label: "風速分布" },
  { from: "先端速度比（tip speed ratio, λ）", to: "出力係数（power coefficient, Cp）", label: "支配" },
  // --- 手法まわり ---
  { from: "渦粘性", to: "ブシネスク仮説", label: "仮定" },
  { from: "RANS（レイノルズ平均ナビエ・ストークス）", to: "ブシネスク仮説", label: "多くが採用" },
  { from: "動的モード分解 (DMD)", to: "サージ", label: "モード抽出" },
  // --- 二次流れの類縁 ---
  { from: "エンドウォール輪郭", to: "コンタリング（endwall contouring）", label: "同概念" },
  // --- 表面粗さと失速近傍の流れ物理（Godse et al. 2024） ---
  { from: "表面粗さ (surface roughness)", to: "エントロピー生成", label: "増大" },
  { from: "衝撃波境界層干渉 (SBLI)", to: "境界層剥離", label: "誘発" },
  { from: "ハブコーナー剥離", to: "ブロッケージ (blockage)", label: "寄与" },
  // --- 翼列内流れ構造とスパイク開始（Hoying et al. 1999） ---
  { from: "先端すき間渦の前縁越え", to: "スパイク型回転失速", label: "引き金" },
  { from: "先端すき間流れ（tip clearance flow）", to: "先端すき間渦の前縁越え", label: "起源" },
  { from: "渦運動学（vortex kinematics）", to: "先端すき間渦の前縁越え", label: "説明手段" },
  // --- コーナー剥離と二面角（Zhu et al. 2026 / Gbadebo et al. 2005） ---
  { from: "LES", to: "WALEモデル", label: "サブグリッドモデル" },
  { from: "二面角 (dihedral angle)", to: "コーナー剥離", label: "強弱を左右" },
  { from: "逆圧力勾配 (adverse pressure gradient)", to: "境界層剥離", label: "誘発" },
  { from: "コーナー剥離", to: "3次元境界層剥離", label: "具体例" },
  { from: "限界流線 (limiting streamline)", to: "3次元境界層剥離", label: "可視化手段" },
  { from: "コーナー剥離", to: "二次流れ", label: "対渦を伴う" },
  // --- 単段圧縮機の回転失速実験（Li et al. 2026） ---
  { from: "スロットル弁", to: "失速境界", label: "閉じて到達" },
  { from: "失速境界", to: "回転失速", label: "移行点" },
  { from: "静翼角度", to: "性能特性（特性曲線）", label: "影響しうる" },
];

const CAT_OF = new Map<string, GraphCategory>();
for (const c of CATEGORIES) for (const t of c.terms) CAT_OF.set(t, c);

export function categoryOf(term: string): GraphCategory | undefined {
  return CAT_OF.get(term);
}
