// 用語の関係マップ（手キュレーション部分）。
// カテゴリ（テーマ分類）と、意味的なエッジ（関係）を定義。
// これに加えて「同じ論文に出た用語どうし」の自動エッジ（共起）をランタイムで合成する。
// term 名は data/papers.json の terms[].term と完全一致させること。

export interface GraphCategory {
  key: string;
  label: string;
  color: string;
  terms: string[];
}

export interface CuratedEdge {
  from: string;
  to: string;
  label?: string;
}

export const CATEGORIES: GraphCategory[] = [
  {
    key: "instability",
    label: "不安定現象",
    color: "#b4451f",
    terms: [
      "サージ",
      "回転失速",
      "B パラメータ",
      "ヘルムホルツ共鳴周波数",
      "スパイク型回転失速",
      "回転失速の前駆現象",
      "モード波型前駆現象 (modal-wave precursor)",
      "深いサージ (deep surge)",
      "Moore–Greitzer モデル",
      "サージ余裕 (surge margin)",
      "入口リサーキュレーション (inlet recirculation)",
      "プリスワール (preswirl)",
      "予旋回角 (pre-rotation angle)",
      "失速余裕",
      "渦崩壊 (vortex breakdown)",
      "逆流（backflow）",
      "ブロッケージ (blockage)",
      "先端すき間渦の前縁越え",
      "渦運動学（vortex kinematics）",
      "失速境界",
      "トルネード型渦",
      "非同期振動 (NSV)",
      "動的失速",
      "動的失速渦 (dynamic stall vortex)",
      "静止失速角 (static stall angle, α_ss)",
      "準定常近似 (quasi-steady approximation)",
      "無次元周波数 k (reduced frequency)",
      "フラッタ",
      "空力弾性",
      "自励振動",
      "キャビテーション",
      "吸気歪み (inlet distortion)",
      "歪み係数DC60 (distortion coefficient)",
      "境界層吸込み (boundary layer ingestion, BLI)",
      "チョーク (choking)",
      "回転不安定現象 (rotating instabilities)",
      "圧縮機長さ半径比",
      "空力弾性不安定",
      "失速誘起振動",
      "古典的フラッタ",
      "非定常空気力学 (unsteady aerodynamics)",
      "プレナム質量バランス法",
      "圧力脈動 (pressure pulsation)",
      "トラベリングウェーブエネルギー (traveling wave energy)",
      "多重安定性 (multistability)",
      "双安定性 (bistability)",
      "三重安定性 (tristability)",
      "流体構造連成 (FSI, fluid-structure interaction)",
      "翼端たわみ (blade-tip deflection)",
      "ディフューザ回転失速 (DRS)",
      "圧力上昇特性の勾配 (characteristic slope)",
      "剥離トポロジー (separation topology)",
      "ケルビン・ヘルムホルツ不安定性 (Kelvin–Helmholtz instability)",
    ],
  },
  {
    key: "loss",
    label: "損失機構",
    color: "#1a5e54",
    terms: [
      "エントロピー生成",
      "エントロピー損失係数",
      "全圧損失係数",
      "翼型損失",
      "D因子 (D-factor)",
      "混合損失",
      "端壁（二次流れ）損失",
      "翼端漏れ",
      "境界層",
      "翼端漏れ渦",
      "翼端漏れ流れ (tip leakage flow)",
      "先端すき間流れ（tip clearance flow）",
      "チップクリアランス (tip clearance, TC)",
      "軸方向渦度 (streamwise vorticity)",
      "表面粗さ (surface roughness)",
      "衝撃波境界層干渉 (SBLI)",
      "剥離泡",
      "再循環（リサーキュレーション）",
      "エロージョン",
      "キャビテーション壊食 (cavitation erosion)",
      "デポジション（堆積）",
      "渦度 (vorticity)",
      "乱流運動エネルギー (turbulent kinetic energy)",
      "斜め衝撃波 (oblique shock wave)",
      "ハブ漏れ流れ (hub leakage flow)",
      "チップ渦（over tip vortex）",
      "乱流境界層",
      "レイノルズせん断応力",
      "翼端漏れジェット (tip leakage jet, TLJ)",
      "内部ギャップせん断流れ (internal gap shear flow)",
      "吐出し係数 (discharge coefficient)",
      "スキーラチップ (squealer tip)",
      "空力損失係数 (aerodynamic loss coefficient)",
      "衝撃波・渦干渉 (shock-vortex interaction)",
      "損失遅れ (loss lag)",
      "渦度輸送方程式 (vorticity transport equation)",
      "渦伸張項 (vortex stretching term)",
      "一次渦 (primary vortex, PV)",
      "二次渦度 (secondary vorticity, SV)",
      "渦合体 (vortex merging)",
    ],
  },
  {
    key: "flow",
    label: "流れ要素・装置",
    color: "#4a6fa5",
    terms: [
      "遠心圧縮機",
      "遠心ポンプ",
      "ボリュートケーシング",
      "多段軸流圧縮機",
      "放射ディフューザ",
      "入射角",
      "せん断層",
      "ターボチャージャー",
      "平面翼列・環状翼列",
      "よどみ点 (stagnation point)",
      "二面角 (dihedral angle)",
      "スロットル弁",
      "静翼角度",
      "レイノルズ数",
      "臨界レイノルズ数",
      "摩擦レイノルズ数 (Re_τ)",
      "乱流強度",
      "ロータ・ステータ干渉",
      "軸方向間隙",
      "循環 (circulation)",
      "回転デトネーション燃焼器 (RDC)",
      "案内羽根",
      "ウォータージェットポンプ",
      "片持ち静翼 (cantilevered stator)",
      "付着渦階層 (attached-eddy hierarchy)",
      "スーパーストラクチャー (superstructures)",
      "可変案内羽根（可変IGV）",
      "ディフューザ静翼",
      "自由流乱れ (freestream turbulence, FST)",
      "摩擦係数 Cf (skin-friction coefficient)",
      "ウルトラハイリフト翼 (ultra-high-lift blade)",
      "低圧タービン (low-pressure turbine, LPT)",
      "ストローハル数 (Strouhal number)",
      "シュリーレン法 (schlieren)",
      "λ型衝撃波足 (lambda shock foot)",
      "羽根車（インペラ）",
      "軸受（すべり軸受）",
      "フルード数 (Froude number)",
      "ストークス数 (Stokes number)",
      "遷音速翼列 (transonic cascade)",
      "平板翼列 (flat-plate cascade)",
      "可変ノズルタービン (VNT, variable nozzle turbine)",
      "リターンチャネル",
      "ポンプ逆転水車 (PAT)",
      "ドラフトチューブ",
      "斜流ポンプ (mixed-flow pump)",
    ],
  },
  {
    key: "method",
    label: "数値解析・手法",
    color: "#7a6a9b",
    terms: [
      "CFD",
      "LES",
      "WALEモデル",
      "サロゲートモデル",
      "CNN",
      "次元削減",
      "転移学習",
      "不確かさ",
      "URANS（k-ω SST）",
      "遺伝的アルゴリズム",
      "動的モード分解 (DMD)",
      "全周非定常RANS (full-annulus URANS)",
      "RANS（レイノルズ平均ナビエ・ストークス）",
      "SST k-ω",
      "k-ω SST乱流モデル",
      "MRF（移動基準座標系）",
      "ブレード通過周波数 (blade passing frequency)",
      "区分的3次多項式",
      "ブシネスク仮説",
      "渦粘性",
      "Q基準 (Q-criterion)",
      "スペクトル固有直交分解 (SPOD)",
      "固有直交分解 (POD)",
      "遅延分離渦シミュレーション (DDES)",
      "薄層近似ナビエ・ストークス方程式",
      "乱流モデル",
      "格子収束性",
      "k-ε RNGモデル",
      "ゾーナルLES (ZLES)",
      "スケール適応シミュレーション (SAS)",
      "ランジュバン方程式 (Langevin equation)",
      "ボロノイ分割 (Voronoi tessellation)",
      "感圧塗料 (PSP, pressure-sensitive paint)",
      "遅延周期境界条件 (lagged periodic boundary condition)",
      "パレート最適解 (Pareto front)",
      "一方向カップリング (one-way coupling)",
      "レイリー後方散乱ひずみセンシング (RBS)",
      "相互相関関数 (cross-correlation function)",
    ],
  },
  {
    key: "theory",
    label: "設計理論・流れ面",
    color: "#8a6d3b",
    terms: [
      "S1流れ面（第一種）",
      "S2流れ面（第二種）",
      "相対流れ面",
      "子午面",
      "子午面安定性予測モデル",
      "スルーフロー理論",
      "主方程式",
      "非粘性流体",
      "順問題・逆問題",
      "性能特性（特性曲線）",
      "負荷係数 / 流量係数",
      "最高効率点（BEP）",
      "非線形オイラー方程式 (nonlinear Euler equations)",
      "基準直径 (reference diameter)",
      "損失相関式 (loss correlation)",
    ],
  },
  {
    key: "control",
    label: "流れ制御・剥離",
    color: "#b9763a",
    terms: [
      "境界層剥離",
      "再付着",
      "シンセティックジェット（合成噴流）",
      "能動流れ制御（AFC）",
      "能動制御 (active control)",
      "迎え角（AoA）",
      "翼負荷分布 (blade loading distribution, BLD)",
      "ケーシングトリートメント",
      "軸方向スロット型ケーシングトリートメント (axial slot casing treatment)",
      "自己再循環",
      "前縁剥離 (leading-edge separation)",
      "3次元境界層剥離",
      "運動量係数 Cμ",
      "無次元周波数 F⁺",
      "渦放出周波数",
      "渦放出 (vortex shedding)",
      "ハブコーナー剥離",
      "コーナー剥離",
      "逆圧力勾配 (adverse pressure gradient)",
      "限界流線 (limiting streamline)",
      "分離ヒステリシス (separation hysteresis)",
      "渦発生器ジェット (vortex generator jet, VGJ)",
      "非定常吹き出し (pulsed blowing)",
      "受動流れ制御",
      "クロッキング (blade row clocking, indexing)",
      "負のジェット (negative jet)",
      "壁面すべり速度",
      "空気噴射 (air injection)",
      "マイクロオフセット翼端 (micro-offset tip)",
      "圧力勾配パラメータβ (Clauser parameter)",
      "漏れジェットの前方吹き出し (forward spillage)",
      "スパンワイズ壁面強制",
      "後縁剥離 (trailing edge separation)",
      "ブレードグルーブ (blade groove)",
    ],
  },
  {
    key: "secondary",
    label: "二次流れ・エンドウォール",
    color: "#5f7a8a",
    terms: [
      "二次流れ",
      "馬蹄形渦（horseshoe vortex）",
      "エンドウォール",
      "エンドウォールフェンス",
      "コンタリング（endwall contouring）",
      "エンドウォール輪郭",
      "径方向流れ再配分",
      "移動端壁 (moving endwall)",
    ],
  },
  {
    key: "transition",
    label: "遷移・伝熱",
    color: "#8f5a6d",
    terms: [
      "層流",
      "乱流",
      "層流-乱流遷移",
      "熱伝達",
      "対流熱伝達係数",
      "フィルム冷却",
      "内部冷却",
      "吹き出し比 (blowing ratio)",
      "シェイプドフィルム孔 (shaped film hole)",
      "断熱膜冷却効率 (adiabatic film effectiveness)",
      "コンパウンド角度噴射 (compound angle injection)",
      "ウェイク誘起遷移 (wake-induced transition)",
      "バイパス遷移 (bypass transition)",
      "疑似層流境界層 (pseudolaminar boundary layer)",
      "負圧面境界層 (suction-side boundary layer)",
      "静穏域 (calmed region)",
      "乱流スポット (turbulent spot)",
      "剥離流遷移 (separated-flow transition)",
    ],
  },
  {
    key: "wake",
    label: "風車・ウェイク",
    color: "#6b8457",
    terms: [
      "後流（ウェイク）",
      "ニアウェイク／ファーウェイク",
      "ウェイクメアンダリング",
      "アクチュエータディスク",
      "大気境界層（ABL）",
      "ヘルマン指数",
      "先端速度比（tip speed ratio, λ）",
      "出力係数（power coefficient, Cp）",
      "推力係数（thrust coefficient, Ct）",
      "固体度（ソリディティ, solidity）",
      "誘導速度場 (induced velocity field)",
      "渦輪 (vortex ring)",
      "後流捕獲 (wake capture)",
      "準定常モデル (quasi-steady model, QS)",
      "付加質量 (added mass)",
      "選択的集積 (preferential concentration)",
      "気泡チェーン (bubble chain)",
      "二段分散 (two-stage dispersion)",
      "自己相似後流 (self-similar wake)",
      "ウェイク誘起揚力 (wake-induced lift)",
      "フェザリング (feathering)",
      "後流減衰 (wake decay)",
      "水平軸風車 (HAWT, horizontal axis wind turbine)",
      "アクチュエータライン (actuator line)",
      "翼端渦 (tip vortex)",
      "根元渦 (root vortex)",
      "自由流乱流強度 (free-stream turbulence, FST)",
    ],
  },
  {
    key: "turbulence",
    label: "乱流理論・カスケード",
    color: "#2f7f8f",
    terms: [
      "エネルギーカスケード",
      "逆カスケード",
      "異方性",
      "超拡散",
      "コヒーレント構造",
      "四象限解析",
      "ストークスひずみ速度 (SSR)",
      "渦対形成 (vortex pairing)",
    ],
  },
];

export const CURATED_EDGES: CuratedEdge[] = [
  { from: "サージ", to: "回転失速", label: "両不安定" },
  { from: "B パラメータ", to: "サージ", label: "支配" },
  { from: "B パラメータ", to: "回転失速", label: "支配" },
  { from: "翼端漏れ", to: "入射角", label: "悪化" },
  { from: "エントロピー生成", to: "エントロピー損失係数", label: "定義" },
  { from: "エントロピー損失係数", to: "全圧損失係数", label: "関係" },
  { from: "境界層", to: "翼型損失", label: "起源" },
  { from: "境界層", to: "せん断層" },
  { from: "翼型損失", to: "エントロピー生成", label: "損失" },
  { from: "端壁（二次流れ）損失", to: "エントロピー生成", label: "損失" },
  { from: "翼端漏れ", to: "エントロピー生成", label: "損失" },
  { from: "混合損失", to: "エントロピー生成", label: "損失" },
  { from: "CFD", to: "LES", label: "一種" },
  { from: "CFD", to: "サロゲートモデル", label: "代替" },
  { from: "サロゲートモデル", to: "CNN", label: "実装" },
  { from: "サロゲートモデル", to: "次元削減" },
  { from: "サロゲートモデル", to: "転移学習" },
  { from: "サロゲートモデル", to: "不確かさ" },
  { from: "遠心圧縮機", to: "サージ", label: "発生" },
  { from: "遠心圧縮機", to: "回転失速", label: "発生" },
  { from: "せん断層", to: "回転失速", label: "渦誘起" },
  { from: "多段軸流圧縮機", to: "サロゲートモデル", label: "対象" },
  { from: "S1流れ面（第一種）", to: "S2流れ面（第二種）", label: "二流れ面" },
  { from: "相対流れ面", to: "S1流れ面（第一種）" },
  { from: "相対流れ面", to: "S2流れ面（第二種）" },
  { from: "S2流れ面（第二種）", to: "スルーフロー理論", label: "基礎" },
  { from: "迎え角（AoA）", to: "境界層剥離", label: "増で誘発" },
  { from: "境界層剥離", to: "再付着", label: "制御で回復" },
  { from: "シンセティックジェット（合成噴流）", to: "境界層剥離", label: "抑制" },
  { from: "能動流れ制御（AFC）", to: "シンセティックジェット（合成噴流）", label: "手段" },
  { from: "能動流れ制御（AFC）", to: "遺伝的アルゴリズム", label: "最適化" },
  { from: "境界層剥離", to: "境界層", label: "から発達" },
  { from: "二次流れ", to: "馬蹄形渦（horseshoe vortex）", label: "起源" },
  { from: "馬蹄形渦（horseshoe vortex）", to: "エンドウォール", label: "境界層から発達" },
  { from: "二次流れ", to: "端壁（二次流れ）損失", label: "損失化" },
  { from: "エンドウォールフェンス", to: "二次流れ", label: "抑制" },
  // --- 不安定現象（スパイク失速・Moore–Greitzer・余裕） ---
  { from: "スパイク型回転失速", to: "回転失速", label: "一型" },
  { from: "回転失速の前駆現象", to: "スパイク型回転失速", label: "前触れ" },
  { from: "深いサージ (deep surge)", to: "サージ", label: "強い形態" },
  { from: "Moore–Greitzer モデル", to: "サージ", label: "予測" },
  { from: "Moore–Greitzer モデル", to: "回転失速", label: "予測" },
  { from: "B パラメータ", to: "Moore–Greitzer モデル", label: "指標" },
  { from: "ヘルムホルツ共鳴周波数", to: "B パラメータ", label: "分母に登場" },
  { from: "サージ余裕 (surge margin)", to: "サージ", label: "距離" },
  { from: "失速余裕", to: "回転失速", label: "距離" },
  { from: "失速余裕", to: "サージ余裕 (surge margin)", label: "類概念" },
  // --- 吸気リサーキュレーション（Ullah et al. 2026） ---
  { from: "入口リサーキュレーション (inlet recirculation)", to: "サージ", label: "悪化で移行" },
  { from: "入口リサーキュレーション (inlet recirculation)", to: "プリスワール (preswirl)", label: "誘起" },
  { from: "プリスワール (preswirl)", to: "入射角", label: "強まると低下" },
  // --- 非対称IGVによる予旋回角と失速誘発（Pan et al. 2026） ---
  { from: "予旋回角 (pre-rotation angle)", to: "プリスワール (preswirl)", label: "類概念" },
  { from: "予旋回角 (pre-rotation angle)", to: "入射角", label: "変化させる" },
  { from: "予旋回角 (pre-rotation angle)", to: "スパイク型回転失速", label: "周方向の漸増域で誘発" },
  // --- 翼端漏れ渦の連鎖（Furukawa 1999）と制御（Yaylak 2026） ---
  { from: "先端すき間流れ（tip clearance flow）", to: "翼端漏れ渦", label: "巻き上がり" },
  { from: "翼端漏れ流れ (tip leakage flow)", to: "翼端漏れ渦", label: "巻き上がり" },
  { from: "翼端漏れ", to: "翼端漏れ渦", label: "同源" },
  { from: "翼端漏れ渦", to: "渦崩壊 (vortex breakdown)", label: "失速近傍で" },
  { from: "渦崩壊 (vortex breakdown)", to: "逆流（backflow）", label: "随伴" },
  { from: "渦崩壊 (vortex breakdown)", to: "ブロッケージ (blockage)", label: "生成" },
  { from: "ブロッケージ (blockage)", to: "回転失速", label: "誘発" },
  { from: "ケーシングトリートメント", to: "翼端漏れ渦", label: "制御" },
  { from: "ケーシングトリートメント", to: "失速余裕", label: "拡大" },
  { from: "自己再循環", to: "ケーシングトリートメント", label: "一種" },
  { from: "軸方向スロット型ケーシングトリートメント (axial slot casing treatment)", to: "ケーシングトリートメント", label: "一種" },
  { from: "モード波型前駆現象 (modal-wave precursor)", to: "回転失速の前駆現象", label: "一型" },
  { from: "D因子 (D-factor)", to: "境界層剥離", label: "予測指標" },
  { from: "前縁剥離 (leading-edge separation)", to: "スパイク型回転失速", label: "引き金" },
  // --- 翼負荷分布とチップクリアランス（Zhou et al. 2026） ---
  { from: "翼負荷分布 (blade loading distribution, BLD)", to: "翼端漏れ流れ (tip leakage flow)", label: "分布を左右" },
  { from: "翼負荷分布 (blade loading distribution, BLD)", to: "失速余裕", label: "後方負荷で拡大" },
  { from: "チップクリアランス (tip clearance, TC)", to: "失速余裕", label: "拡大で悪化" },
  { from: "能動制御 (active control)", to: "回転失速", label: "抑制/脱出" },
  { from: "能動制御 (active control)", to: "サージ", label: "抑制/脱出" },
  // --- 遷移・伝熱（Mayle 1991） ---
  { from: "層流", to: "層流-乱流遷移", label: "始点" },
  { from: "層流-乱流遷移", to: "乱流", label: "終点" },
  { from: "層流-乱流遷移", to: "境界層", label: "内で進行" },
  { from: "層流-乱流遷移", to: "熱伝達", label: "左右" },
  // --- フィルム冷却（Bunker 2005） ---
  { from: "シェイプドフィルム孔 (shaped film hole)", to: "フィルム冷却", label: "発展形" },
  { from: "シェイプドフィルム孔 (shaped film hole)", to: "断熱膜冷却効率 (adiabatic film effectiveness)", label: "向上させる" },
  { from: "吹き出し比 (blowing ratio)", to: "断熱膜冷却効率 (adiabatic film effectiveness)", label: "左右する" },
  // --- 風車・ウェイク（Sanderse 2011 / Vilotijević 2026） ---
  { from: "ニアウェイク／ファーウェイク", to: "後流（ウェイク）", label: "区分" },
  { from: "ウェイクメアンダリング", to: "後流（ウェイク）", label: "揺動" },
  { from: "アクチュエータディスク", to: "後流（ウェイク）", label: "模擬" },
  { from: "大気境界層（ABL）", to: "後流（ウェイク）", label: "流入条件" },
  { from: "ヘルマン指数", to: "大気境界層（ABL）", label: "風速分布" },
  { from: "先端速度比（tip speed ratio, λ）", to: "出力係数（power coefficient, Cp）", label: "支配" },
  // --- 手法まわり ---
  { from: "渦粘性", to: "ブシネスク仮説", label: "仮定" },
  { from: "RANS（レイノルズ平均ナビエ・ストークス）", to: "ブシネスク仮説", label: "多くが採用" },
  { from: "動的モード分解 (DMD)", to: "サージ", label: "モード抽出" },
  // --- 二次流れの類縁 ---
  { from: "エンドウォール輪郭", to: "コンタリング（endwall contouring）", label: "同概念" },
  // --- 表面粗さと失速近傍の流れ物理（Godse et al. 2024） ---
  { from: "表面粗さ (surface roughness)", to: "エントロピー生成", label: "増大" },
  { from: "衝撃波境界層干渉 (SBLI)", to: "境界層剥離", label: "誘発" },
  { from: "ハブコーナー剥離", to: "ブロッケージ (blockage)", label: "寄与" },
  // --- 翼列内流れ構造とスパイク開始（Hoying et al. 1999） ---
  { from: "先端すき間渦の前縁越え", to: "スパイク型回転失速", label: "引き金" },
  { from: "先端すき間流れ（tip clearance flow）", to: "先端すき間渦の前縁越え", label: "起源" },
  { from: "渦運動学（vortex kinematics）", to: "先端すき間渦の前縁越え", label: "説明手段" },
  // --- コーナー剥離と二面角（Zhu et al. 2026 / Gbadebo et al. 2005） ---
  { from: "LES", to: "WALEモデル", label: "サブグリッドモデル" },
  { from: "二面角 (dihedral angle)", to: "コーナー剥離", label: "強弱を左右" },
  { from: "逆圧力勾配 (adverse pressure gradient)", to: "境界層剥離", label: "誘発" },
  { from: "コーナー剥離", to: "3次元境界層剥離", label: "具体例" },
  { from: "限界流線 (limiting streamline)", to: "3次元境界層剥離", label: "可視化手段" },
  { from: "コーナー剥離", to: "二次流れ", label: "対渦を伴う" },
  // --- 単段圧縮機の回転失速実験（Li et al. 2026） ---
  { from: "スロットル弁", to: "失速境界", label: "閉じて到達" },
  { from: "失速境界", to: "回転失速", label: "移行点" },
  { from: "静翼角度", to: "性能特性（特性曲線）", label: "影響しうる" },
  // --- ファン翼のSBLI実験（Hanfy et al. 2026） ---
  { from: "レイノルズ数", to: "層流-乱流遷移", label: "低いほど遅延" },
  { from: "乱流強度", to: "層流-乱流遷移", label: "促進" },
  { from: "剥離泡", to: "衝撃波境界層干渉 (SBLI)", label: "随伴" },
  { from: "剥離泡", to: "境界層剥離", label: "一形態" },
  // --- タービン高温ガスパスの伝熱課題（Bunker 2007） ---
  { from: "フィルム冷却", to: "熱伝達", label: "冷却手段" },
  { from: "内部冷却", to: "熱伝達", label: "冷却手段" },
  // --- 遠心ポンプのケーシング影響（Rehman et al. 2026） ---
  { from: "遠心ポンプ", to: "ボリュートケーシング", label: "構成" },
  { from: "ボリュートケーシング", to: "再循環（リサーキュレーション）", label: "低流量時に誘発" },
  { from: "再循環（リサーキュレーション）", to: "エントロピー生成", label: "損失" },
  // --- タービン機械のエロージョン・デポジション（Hamed et al. 2006） ---
  { from: "エロージョン", to: "デポジション（堆積）", label: "対照的な劣化現象" },
  // --- 翼端漏れ渦のSPODモード解析（He et al. 2021） ---
  { from: "スペクトル固有直交分解 (SPOD)", to: "固有直交分解 (POD)", label: "エネルギー順位付けを継承" },
  { from: "スペクトル固有直交分解 (SPOD)", to: "動的モード分解 (DMD)", label: "周波数分解を継承" },
  { from: "遅延分離渦シミュレーション (DDES)", to: "LES", label: "遠方はLES的に解く" },
  { from: "翼端漏れ渦", to: "非同期振動 (NSV)", label: "誘発しうる" },
  { from: "翼端漏れ渦", to: "スペクトル固有直交分解 (SPOD)", label: "モード解析対象" },
  // --- 3段軸流圧縮機のRe依存失速機構切り替え（Zhou et al. 2024） ---
  { from: "レイノルズ数", to: "臨界レイノルズ数", label: "しきい値" },
  { from: "臨界レイノルズ数", to: "回転失速", label: "下回ると失速機構が変化" },
  { from: "径方向流れ再配分", to: "翼端漏れ流れ (tip leakage flow)", label: "低Reで顕著化" },
  // --- ロータ・ステータ干渉のCFD（Rai 1987） ---
  { from: "ロータ・ステータ干渉", to: "軸方向間隙", label: "隙間が狭いほど強まる" },
  // --- 先端すき間流れの粘性損失機構（You et al. 2007） ---
  { from: "翼端漏れ渦", to: "渦度 (vorticity)", label: "強い渦度を伴う" },
  { from: "渦度 (vorticity)", to: "乱流運動エネルギー (turbulent kinetic energy)", label: "生成に寄与" },
  { from: "乱流運動エネルギー (turbulent kinetic energy)", to: "エントロピー生成", label: "生成源" },
  // --- RDC-タービン結合系の前縁・エンドウォール冷却（Zhou et al. 2025） ---
  { from: "回転デトネーション燃焼器 (RDC)", to: "斜め衝撃波 (oblique shock wave)", label: "燃焼室下流に生成" },
  { from: "吹き出し比 (blowing ratio)", to: "フィルム冷却", label: "冷却効率を左右" },
  { from: "フィルム冷却", to: "エンドウォール", label: "適用面" },
  // --- VAWTの乱流モデル精度検証（Rezaeiha et al. 2019） ---
  { from: "乱流モデル", to: "SST k-ω", label: "系統の一つ" },
  { from: "動的失速", to: "SST k-ω", label: "遷移版が精度良く予測" },
  { from: "格子収束性", to: "乱流モデル", label: "検証の前提条件" },
  // --- ウォータージェットポンプのキャビテーション振動（Long et al. 2026） ---
  { from: "キャビテーション", to: "NPSH（有効吸込みヘッド）", label: "不足で発生" },
  { from: "キャビテーション", to: "羽根車（インペラ）", label: "翼まわりで発生・振動誘発" },
  { from: "案内羽根", to: "ウォータージェットポンプ", label: "構成要素" },
  // --- 片持ち静翼のハブ漏れ流れと翼負荷分布（Liu et al. 2026） ---
  { from: "片持ち静翼 (cantilevered stator)", to: "ハブ漏れ流れ (hub leakage flow)", label: "隙間から発生" },
  { from: "ハブ漏れ流れ (hub leakage flow)", to: "翼端漏れ流れ (tip leakage flow)", label: "対称的な現象（ハブ側）" },
  { from: "移動端壁 (moving endwall)", to: "ハブ漏れ流れ (hub leakage flow)", label: "漏れ渦の発達位置を左右" },
  // --- 横風によるジェットエンジンインテーク歪みとヒステリシス（Harjes et al. 2020） ---
  { from: "吸気歪み (inlet distortion)", to: "分離ヒステリシス (separation hysteresis)", label: "強い歪みで発生" },
  { from: "分離ヒステリシス (separation hysteresis)", to: "境界層剥離", label: "剥離・再付着の履歴依存" },
  { from: "歪み係数DC60 (distortion coefficient)", to: "吸気歪み (inlet distortion)", label: "定量指標" },
  // --- 高Re逆圧力勾配境界層の壁面付着渦とせん断層（Zarei et al. 2026） ---
  { from: "摩擦レイノルズ数 (Re_τ)", to: "レイノルズ数", label: "壁面基準の定義" },
  { from: "付着渦階層 (attached-eddy hierarchy)", to: "境界層", label: "近壁の階層構造" },
  { from: "スーパーストラクチャー (superstructures)", to: "付着渦階層 (attached-eddy hierarchy)", label: "最大スケール側" },
  { from: "逆圧力勾配 (adverse pressure gradient)", to: "せん断層", label: "外層で活動を強化" },
  // --- パルス駆動渦発生器ジェットによるタービン剥離制御（Bons et al. 2000） ---
  { from: "渦発生器ジェット (vortex generator jet, VGJ)", to: "境界層剥離", label: "抑制" },
  { from: "非定常吹き出し (pulsed blowing)", to: "渦発生器ジェット (vortex generator jet, VGJ)", label: "駆動方式" },
  // --- 小型VAWTの風洞実験×CFD比較（Howell et al. 2009） ---
  { from: "チップ渦（over tip vortex）", to: "出力係数（power coefficient, Cp）", label: "2D計算では再現されず過大評価を招く" },
  { from: "固体度（ソリディティ, solidity）", to: "先端速度比（tip speed ratio, λ）", label: "高いほど低TSRでピーク" },
  // --- BLI推進系ファンの流入歪み（Magrini & Benini 2026） ---
  { from: "境界層吸込み (boundary layer ingestion, BLI)", to: "吸気歪み (inlet distortion)", label: "誘発" },
  // --- 受動回転ディスクによる乱流境界層の抵抗低減（Knoop & Ricco 2026） ---
  { from: "乱流境界層", to: "レイノルズせん断応力", label: "内部で運動量を輸送" },
  { from: "レイノルズせん断応力", to: "境界層", label: "壁面摩擦の主要な担い手" },
  { from: "受動流れ制御", to: "表面粗さ (surface roughness)", label: "回転体まわりに粗さ的効果を生む" },
  { from: "壁面すべり速度", to: "受動流れ制御", label: "回転運動がもたらす効果の一つ" },
  // --- 異方的フーリエ空間の2次元乱流モデル（Carbone & Servidio 2026） ---
  { from: "逆カスケード", to: "エネルギーカスケード", label: "大スケールへ運ぶ一種" },
  { from: "異方性", to: "逆カスケード", label: "効率を左右" },
  { from: "超拡散", to: "渦度 (vorticity)", label: "渦へのトラップ&放出で発生" },
  // --- ロータ・ステータ間隔とウェイク渦放出の性能相関（Yu et al. 2026） ---
  { from: "渦放出 (vortex shedding)", to: "循環 (circulation)", label: "強さを循環で定量化" },
  { from: "渦放出 (vortex shedding)", to: "コーナー剥離", label: "スパン方向渦放出が周期的に抑制" },
  { from: "ロータ・ステータ干渉", to: "渦放出 (vortex shedding)", label: "間隔が狭いほど誘発" },
  // --- 軸流圧縮機の失速・サージ能動抑制（Day 1993） ---
  { from: "空気噴射 (air injection)", to: "能動流れ制御（AFC）", label: "実現手段" },
  { from: "空気噴射 (air injection)", to: "モード波型前駆現象 (modal-wave precursor)", label: "検知して減衰" },
  // --- 翼端漏れ流れが励起する自励的非定常性とその制御（Liu et al. 2024） ---
  { from: "翼端漏れジェット (tip leakage jet, TLJ)", to: "翼端漏れ渦", label: "せん断で巻き上げる" },
  { from: "ゾーナルLES (ZLES)", to: "LES", label: "翼端近傍だけLES化" },
  { from: "マイクロオフセット翼端 (micro-offset tip)", to: "翼端漏れ渦", label: "ワンダリングを抑制" },
  // --- 軸流圧縮系の失速後過渡現象パートII（Greitzer & Moore 1986） ---
  { from: "圧縮機長さ半径比", to: "サージ", label: "小さいほど誘発" },
  { from: "圧縮機長さ半径比", to: "B パラメータ", label: "共にサージ/回転失速の分岐を支配" },
  // --- 高速圧縮機のモーダル前駆波（Tryfonidis et al. 1995） ---
  { from: "トラベリングウェーブエネルギー (traveling wave energy)", to: "モード波型前駆現象 (modal-wave precursor)", label: "実時間の安定性指標" },
  { from: "トラベリングウェーブエネルギー (traveling wave energy)", to: "Moore–Greitzer モデル", label: "低次元理論の予測を補完" },
  // --- 眼科医療センター向けTDCPの圧力脈動（Gong et al. 2026） ---
  { from: "圧力脈動 (pressure pulsation)", to: "ロータ・ステータ干渉", label: "決定論的な駆動源の一つ" },
  { from: "圧力脈動 (pressure pulsation)", to: "渦放出 (vortex shedding)", label: "低周波成分の起源になりうる" },
  { from: "ストローハル数 (Strouhal number)", to: "渦放出 (vortex shedding)", label: "放出周波数を無次元化" },
  { from: "スケール適応シミュレーション (SAS)", to: "RANS（レイノルズ平均ナビエ・ストークス）", label: "渦粘性を動的に低減して拡張" },
  { from: "スケール適応シミュレーション (SAS)", to: "LES", label: "分離域でLES的挙動に近づく" },
  // --- 自由流乱れが逆圧力勾配境界層に与える影響（Jaroslawski & Scarano 2026） ---
  { from: "自由流乱れ (freestream turbulence, FST)", to: "乱流境界層", label: "内部に浸透し発達を左右" },
  { from: "自由流乱れ (freestream turbulence, FST)", to: "逆圧力勾配 (adverse pressure gradient)", label: "及ぼす効果を打ち消す" },
  { from: "圧力勾配パラメータβ (Clauser parameter)", to: "逆圧力勾配 (adverse pressure gradient)", label: "強さを定量化" },
  // --- 低圧タービンの後流誘起遷移とハイリフト翼（Hodson & Howell 2005） ---
  { from: "後流（ウェイク）", to: "負圧面境界層 (suction-side boundary layer)", label: "干渉して遷移を誘発" },
  { from: "ウェイク誘起遷移 (wake-induced transition)", to: "ウルトラハイリフト翼 (ultra-high-lift blade)", label: "効果を利用して実現" },
  { from: "ウルトラハイリフト翼 (ultra-high-lift blade)", to: "低圧タービン (low-pressure turbine, LPT)", label: "損失抑制のための翼設計" },
  // --- 可変IGVによる軸流ポンプの性能改善とキャビテーション抑制（Nguyen et al. 2026） ---
  { from: "可変案内羽根（可変IGV）", to: "案内羽根", label: "一種（角度可変）" },
  { from: "可変案内羽根（可変IGV）", to: "キャビテーション", label: "角度で抑制・悪化を左右" },
  { from: "可変案内羽根（可変IGV）", to: "翼端漏れ渦", label: "角度が渦軌跡を左右" },
  { from: "案内羽根", to: "ディフューザ静翼", label: "下流側の対の静翼列" },
  { from: "最高効率点（BEP）", to: "性能特性（特性曲線）", label: "評価の基準点" },
  // --- 風車の空力弾性不安定（Hansen 2007） ---
  { from: "空力弾性不安定", to: "失速誘起振動", label: "一型（失速型風車）" },
  { from: "空力弾性不安定", to: "古典的フラッタ", label: "一型（ピッチ制御型風車）" },
  { from: "構造減衰", to: "失速誘起振動", label: "負の空力減衰を相殺" },
  { from: "ねじり剛性", to: "古典的フラッタ", label: "低いほど誘発" },
  { from: "翼端速度", to: "古典的フラッタ", label: "大きいほど誘発" },
  // --- ウェイク誘起層流-乱流遷移の診断手法（Suprun 2026） ---
  { from: "後流（ウェイク）", to: "ウェイク誘起遷移 (wake-induced transition)", label: "引き起こす" },
  { from: "ウェイク誘起遷移 (wake-induced transition)", to: "層流-乱流遷移", label: "一形態" },
  { from: "バイパス遷移 (bypass transition)", to: "層流-乱流遷移", label: "一形態" },
  { from: "ウェイク誘起遷移 (wake-induced transition)", to: "疑似層流境界層 (pseudolaminar boundary layer)", label: "先行区間" },
  // --- 軸流圧縮機のサージ・回転失速の実験検証（Greitzer 1976 Part II） ---
  { from: "プレナム質量バランス法", to: "サージ", label: "定量計測に使用" },
  { from: "プレナム質量バランス法", to: "回転失速", label: "定量計測に使用" },
  // --- 多段遠心圧縮機ディフューザのトルネード型渦（Zhong et al. 2026） ---
  { from: "逆圧力勾配 (adverse pressure gradient)", to: "トルネード型渦", label: "強い剥離とともに誘発" },
  { from: "トルネード型渦", to: "ブロッケージ (blockage)", label: "通路を閉塞" },
  { from: "トルネード型渦", to: "回転失速", label: "旋回失速の引き金" },
  // --- 多段翼列の後流誘起境界層遷移（Halstead et al. 1997） ---
  { from: "乱流スポット (turbulent spot)", to: "静穏域 (calmed region)", label: "後方に生成" },
  { from: "静穏域 (calmed region)", to: "層流-乱流遷移", label: "剥離抑制・遷移遅延" },
  { from: "ウェイク誘起遷移 (wake-induced transition)", to: "乱流スポット (turbulent spot)", label: "ウェイク経路で生成" },
  { from: "剥離流遷移 (separated-flow transition)", to: "層流-乱流遷移", label: "一形態" },
  // --- 双子角柱後流の多重安定性（Barlet et al. 2026） ---
  { from: "双安定性 (bistability)", to: "多重安定性 (multistability)", label: "状態が2つの場合" },
  { from: "三重安定性 (tristability)", to: "多重安定性 (multistability)", label: "状態が3つの場合" },
  { from: "後流（ウェイク）", to: "多重安定性 (multistability)", label: "双子後流で発現" },
  { from: "ランジュバン方程式 (Langevin equation)", to: "多重安定性 (multistability)", label: "状態遷移をモデル化" },
  // --- 大型タービンエンドウォールの熱伝達・フィルム冷却（Blair 1974） ---
  { from: "二次流れ", to: "対流熱伝達係数", label: "分布を不均一化" },
  // --- 風車の非定常空気力学モデリングの課題（Leishman 2002） ---
  { from: "非定常空気力学 (unsteady aerodynamics)", to: "動的失速", label: "代表的な非線形現象" },
  { from: "非定常空気力学 (unsteady aerodynamics)", to: "古典的フラッタ", label: "関連する不安定現象" },
  { from: "誘導速度場 (induced velocity field)", to: "後流（ウェイク）", label: "後流の渦が誘起" },
  // --- 反転する平板の後流捕獲（de Boer & Buchner 2026） ---
  { from: "後流捕獲 (wake capture)", to: "後流（ウェイク）", label: "後流との再相互作用" },
  { from: "後流捕獲 (wake capture)", to: "渦輪 (vortex ring)", label: "渦輪の位置・強さに支配される" },
  { from: "準定常モデル (quasi-steady model, QS)", to: "付加質量 (added mass)", label: "モデルの構成要素" },
  { from: "渦輪 (vortex ring)", to: "循環 (circulation)", label: "強さを循環で定量化" },
  { from: "誘導速度場 (induced velocity field)", to: "渦輪 (vortex ring)", label: "渦輪が誘起する速度場の一種" },
  // --- 円柱後流の粒子選択的集積と重力（Arya & Goswami 2026） ---
  { from: "ストークス数 (Stokes number)", to: "選択的集積 (preferential concentration)", label: "値が1程度で最も強く発現" },
  { from: "フルード数 (Froude number)", to: "選択的集積 (preferential concentration)", label: "小さいほど重力が支配し弱める" },
  { from: "ボロノイ分割 (Voronoi tessellation)", to: "選択的集積 (preferential concentration)", label: "空隙・クラスタを定量化" },
  // --- 軸受のキャビテーション（Dowson & Taylor 1979） ---
  { from: "キャビテーション", to: "キャビテーション壊食 (cavitation erosion)", label: "崩壊時の衝撃で発生" },
  { from: "軸受（すべり軸受）", to: "キャビテーション", label: "油膜内で発生しうる" },
  { from: "キャビテーション壊食 (cavitation erosion)", to: "羽根車（インペラ）", label: "代表的な被害部品" },
  // --- 翼端すきま損失の内訳（Bindon 1989） ---
  { from: "剥離泡", to: "混合損失", label: "圧力勾配消失後の巻き込みで発生" },
  { from: "内部ギャップせん断流れ (internal gap shear flow)", to: "翼端漏れ流れ (tip leakage flow)", label: "すきま内のせん断損失成分" },
  { from: "吐出し係数 (discharge coefficient)", to: "翼端漏れ流れ (tip leakage flow)", label: "低減はかえって損失を増やしうる" },
  // --- 気泡チェーンの遠方後流重ね合わせ（Suzuki, Kusuno & Sanada 2026） ---
  { from: "気泡チェーン (bubble chain)", to: "自己相似後流 (self-similar wake)", label: "個々の気泡が生成" },
  { from: "自己相似後流 (self-similar wake)", to: "ニアウェイク／ファーウェイク", label: "遠方後流の記述に使う解" },
  { from: "ウェイク誘起揚力 (wake-induced lift)", to: "二段分散 (two-stage dispersion)", label: "第1段の横移動を駆動" },
  { from: "二段分散 (two-stage dispersion)", to: "気泡チェーン (bubble chain)", label: "分散過程" },
  { from: "レイノルズ数", to: "抗力係数 (drag coefficient, C_D)", label: "値とともに変化" },
  // --- 翼端漏れジェットの前方吹き出しとスパイク発生（Hewkin-Smith et al. 2019） ---
  { from: "翼端漏れジェット (tip leakage jet, TLJ)", to: "漏れジェットの前方吹き出し (forward spillage)", label: "運動量増大で優勢化" },
  { from: "漏れジェットの前方吹き出し (forward spillage)", to: "前縁剥離 (leading-edge separation)", label: "高迎角の一因" },
  { from: "コーナー剥離", to: "漏れジェットの前方吹き出し (forward spillage)", label: "すきま拡大で主役交代" },
  { from: "漏れジェットの前方吹き出し (forward spillage)", to: "失速余裕", label: "優勢化で流量範囲を縮小" },
  // --- 法線衝撃波境界層干渉の実験的SPOD解析（Riveiro Moreno et al. 2026） ---
  { from: "λ型衝撃波足 (lambda shock foot)", to: "衝撃波境界層干渉 (SBLI)", label: "干渉部に形成される構造" },
  { from: "シュリーレン法 (schlieren)", to: "スペクトル固有直交分解 (SPOD)", label: "撮影画像にモード分解を適用" },
  { from: "斜め衝撃波 (oblique shock wave)", to: "λ型衝撃波足 (lambda shock foot)", label: "後方脚を構成" },
  { from: "スペクトル固有直交分解 (SPOD)", to: "再付着", label: "渦放出モードが再付着線から出現" },
  // --- 抗力低減乱流境界層のコヒーレント構造と回復現象（Bistriceanu et al. 2026） ---
  { from: "スパンワイズ壁面強制", to: "レイノルズせん断応力", label: "近壁構造を乱して抑制" },
  { from: "コヒーレント構造", to: "レイノルズせん断応力", label: "主な担い手" },
  { from: "四象限解析", to: "コヒーレント構造", label: "噴出・掃流の型を検出" },
  // --- 航空機フラッタの歴史的発展（Garrick & Reed 1981） ---
  { from: "フラッタ", to: "空力弾性", label: "現象の一側面" },
  { from: "自励振動", to: "フラッタ", label: "発生機構" },
  { from: "フラッタ", to: "ねじり剛性", label: "低いほど発生しやすい" },
  // --- タービン動翼翼端の台形スロット・リブスロット冷却（Xia, Zhang & Hu 2026） ---
  { from: "スキーラチップ (squealer tip)", to: "翼端漏れ流れ (tip leakage flow)", label: "先端形状で抑制" },
  { from: "感圧塗料 (PSP, pressure-sensitive paint)", to: "断熱膜冷却効率 (adiabatic film effectiveness)", label: "光学的に計測する手法" },
  { from: "空力損失係数 (aerodynamic loss coefficient)", to: "翼端漏れ流れ (tip leakage flow)", label: "翼端漏れが増大させる指標" },
  // --- 非定常ウェイク・ロータ相互作用の計算（Giles 1988） ---
  { from: "非線形オイラー方程式 (nonlinear Euler equations)", to: "ロータ・ステータ干渉", label: "非定常解析の基礎方程式" },
  { from: "遅延周期境界条件 (lagged periodic boundary condition)", to: "ロータ・ステータ干渉", label: "ピッチ不一致から生じる境界条件" },
  { from: "遺伝的アルゴリズム", to: "パレート最適解 (Pareto front)", label: "探索" },
  { from: "損失相関式 (loss correlation)", to: "全圧損失係数", label: "予測" },
  { from: "基準直径 (reference diameter)", to: "損失相関式 (loss correlation)", label: "計算の基準" },
  // --- 不均一な先端すきまとVNTの漏れ渦・衝撃波干渉（Luo, Xiang, Lei, Liu & Zhang 2026） ---
  { from: "チップクリアランス (tip clearance, TC)", to: "翼端漏れ渦", label: "拡大すると渦が強まる" },
  { from: "翼端漏れ渦", to: "衝撃波・渦干渉 (shock-vortex interaction)", label: "超音速翼列では衝撃波と干渉し損失を増大" },
  { from: "可変ノズルタービン (VNT, variable nozzle turbine)", to: "チップクリアランス (tip clearance, TC)", label: "ノズルベーン先端すきまが性能を左右" },
  // --- 風車翼のCFD-FEA一方向FSIモデリング（Wang, Quant & Kolios 2016） ---
  { from: "流体構造連成 (FSI, fluid-structure interaction)", to: "空力弾性", label: "現象を引き起こす相互作用" },
  { from: "流体構造連成 (FSI, fluid-structure interaction)", to: "翼端たわみ (blade-tip deflection)", label: "荷重がたわみを生む" },
  { from: "一方向カップリング (one-way coupling)", to: "流体構造連成 (FSI, fluid-structure interaction)", label: "簡易的な結合方式" },
  // --- ディフューザ回転失速の穴あき抑制（Yanagihara et al. 2025） ---
  { from: "ディフューザ回転失速 (DRS)", to: "回転失速", label: "一種（ディフューザ内で発生）" },
  { from: "リターンチャネル", to: "ディフューザ回転失速 (DRS)", label: "圧力差をジェット流の駆動源として抑制に利用" },
  { from: "前縁剥離 (leading-edge separation)", to: "ディフューザ回転失速 (DRS)", label: "剥離渦の負圧コアが誘発" },
  { from: "受動流れ制御", to: "ディフューザ回転失速 (DRS)", label: "穴からのジェット流で抑制" },
  // --- PATのエントロピー生成による損失機構（Ghorani et al. 2020） ---
  { from: "ポンプ逆転水車 (PAT)", to: "エントロピー生成", label: "各部品別に定量化" },
  { from: "ドラフトチューブ", to: "エントロピー生成", label: "体積あたりで最も生成しやすい部品" },
  { from: "羽根車（インペラ）", to: "エントロピー生成", label: "総量の半分超が発生" },
  // --- モード/スパイク統一枠組み（Grimshaw et al. 2025） ---
  { from: "圧力上昇特性の勾配 (characteristic slope)", to: "モード波型前駆現象 (modal-wave precursor)", label: "緩やかな正勾配で成長" },
  { from: "圧力上昇特性の勾配 (characteristic slope)", to: "スパイク型回転失速", label: "急な正勾配で急成長" },
  { from: "剥離トポロジー (separation topology)", to: "圧力上昇特性の勾配 (characteristic slope)", label: "急激な剥離ほど勾配を急にする" },
  // --- 斜流ポンプの後流渦とエントロピー生成（Chen et al. 2026） ---
  { from: "斜流ポンプ (mixed-flow pump)", to: "羽根車（インペラ）", label: "構成" },
  { from: "斜流ポンプ (mixed-flow pump)", to: "案内羽根", label: "構成" },
  { from: "斜流ポンプ (mixed-flow pump)", to: "遠心ポンプ", label: "遠心ポンプと軸流ポンプの中間的な流れ方" },
  { from: "動的モード分解 (DMD)", to: "ロータ・ステータ干渉", label: "支配モードとして検出" },
  { from: "翼端漏れ渦", to: "エントロピー生成", label: "翼端すきま近傍で散逸が集中" },
  // --- 静翼クロッキングと後流-翼干渉（Taghavi Zenouz & Abiri 2026） ---
  { from: "クロッキング (blade row clocking, indexing)", to: "受動流れ制御", label: "一種（周方向インデックスで調整）" },
  { from: "クロッキング (blade row clocking, indexing)", to: "ロータ・ステータ干渉", label: "後流と下流翼列の衝突位置を調整" },
  { from: "負のジェット (negative jet)", to: "後流（ウェイク）", label: "再配向の過程で生じる" },
  { from: "負のジェット (negative jet)", to: "全圧損失係数", label: "前縁への衝突位置次第で損失を左右" },
  // --- 風車後流のレビュー（Vermeer, Sørensen & Crespo 2003） ---
  { from: "後流減衰 (wake decay)", to: "ニアウェイク／ファーウェイク", label: "ファーウェイクで進む現象" },
  // --- 準定常近似の破綻（Malarczyk & Hultmark 2026） ---
  { from: "準定常近似 (quasi-steady approximation)", to: "無次元周波数 k (reduced frequency)", label: "小さいkで妥当と仮定" },
  { from: "動的失速", to: "動的失速渦 (dynamic stall vortex)", label: "境界層剥離の巻き上がりで形成" },
  { from: "静止失速角 (static stall angle, α_ss)", to: "動的失速", label: "通過が引き金になりうる" },
  // --- PATのチップ漏れ流れによる損失（Kan et al. 2022） ---
  { from: "翼端漏れ渦", to: "渦度輸送方程式 (vorticity transport equation)", label: "空間的な発達を記述" },
  { from: "渦度輸送方程式 (vorticity transport equation)", to: "渦伸張項 (vortex stretching term)", label: "発達の支配項として同定" },
  { from: "水平軸風車 (HAWT, horizontal axis wind turbine)", to: "後流（ウェイク）", label: "後流を生む対象" },
  // --- ブレードグルーブによるコーナー剥離・後縁剥離の同時制御（Yao et al. 2026） ---
  { from: "ブレードグルーブ (blade groove)", to: "コーナー剥離", label: "溝ジェットで抑制" },
  { from: "ブレードグルーブ (blade groove)", to: "後縁剥離 (trailing edge separation)", label: "配置次第で抑制/悪化" },
  { from: "コーナー剥離", to: "後縁剥離 (trailing edge separation)", label: "抑制で逆圧力勾配増→悪化しうる" },
  // --- 風車後流LESにおけるアクチュエータライン／ディスクモデルの比較（Martínez-Tossas et al. 2014） ---
  { from: "アクチュエータライン (actuator line)", to: "アクチュエータディスク", label: "比較対象のロータ表現モデル" },
  { from: "アクチュエータライン (actuator line)", to: "翼端渦 (tip vortex)", label: "翼近傍で生成できる" },
  { from: "翼端渦 (tip vortex)", to: "根元渦 (root vortex)", label: "ともに翼近傍の後流構造" },
  // --- 翼型遷移流れにおける渦合体と抗力急増（Gautam & Prasad 2026） ---
  { from: "ケルビン・ヘルムホルツ不安定性 (Kelvin–Helmholtz instability)", to: "せん断層", label: "巻き上がりを駆動" },
  { from: "せん断層", to: "一次渦 (primary vortex, PV)", label: "巻き上がって形成" },
  { from: "一次渦 (primary vortex, PV)", to: "二次渦度 (secondary vorticity, SV)", label: "壁面に逆符号の渦度層を誘起" },
  { from: "二次渦度 (secondary vorticity, SV)", to: "一次渦 (primary vortex, PV)", label: "噴出してせん断層から切り離す" },
  { from: "一次渦 (primary vortex, PV)", to: "渦合体 (vortex merging)", label: "接近した複数個が後縁近傍で合体" },
  { from: "渦合体 (vortex merging)", to: "後縁剥離 (trailing edge separation)", label: "合体域が後縁の吸引ピークと重なる" },
  // --- 模型風車の翼-後流結合の相互相関解析（de Oliveira et al. 2026） ---
  { from: "レイリー後方散乱ひずみセンシング (RBS)", to: "相互相関関数 (cross-correlation function)", label: "後流計測と組み合わせ結合を解析" },
  { from: "先端速度比（tip speed ratio, λ）", to: "自由流乱流強度 (free-stream turbulence, FST)", label: "運転条件を特徴づける独立因子" },
  { from: "せん断層", to: "コヒーレント構造", label: "翼端渦などが局在" },
  // --- 渦を伴うキャビテーションのレビュー（Arndt 2002） ---
  { from: "渦度 (vorticity)", to: "キャビテーション", label: "渦芯の低圧で誘発" },
  { from: "キャビテーション", to: "渦度 (vorticity)", label: "渦度生成の機構にもなりうる" },
  { from: "渦対形成 (vortex pairing)", to: "キャビテーション", label: "噴流中での発生機構" },
];

const CAT_OF = new Map<string, GraphCategory>();
for (const c of CATEGORIES) for (const t of c.terms) CAT_OF.set(t, c);

export function categoryOf(term: string): GraphCategory | undefined {
  return CAT_OF.get(term);
}
